# Generated by Django 5.1.3 on 2025-04-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='photo',
            field=models.ImageField(blank=True, default='products/no_image.png', null=True, upload_to='products/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='photo',
            field=models.ImageField(blank=True, default='products/no_image.png', null=True, upload_to='products/', verbose_name='Photo'),
        ),
    ]
