# Generated by Django 5.1.3 on 2025-04-19 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='data_type',
            field=models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('choice', 'Список')], default='text', max_length=10, verbose_name='Тип значения'),
        ),
        migrations.CreateModel(
            name='AttributeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Вариант')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='catalog.attribute', verbose_name='Атрибут')),
            ],
        ),
    ]
