# Generated by Django 5.1.3 on 2025-04-19 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_attribute_data_type_attributechoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='data_type',
        ),
        migrations.DeleteModel(
            name='AttributeChoice',
        ),
    ]
